### PR TITLE
[PROPOSAL] 🐣 session and participant factories;

### PR DESCRIPTION
**Pull request by kirilknysh**

### CODE REVIEW

**Comment by kirilknysh** [comment]
@DaQuirm , good question. Some params are optional for some messages (e.g. `displayName`).
Do we want to be so strict? A bit worry about performance...

**Comment by DaQuirm** [comment]
@kirilknysh I'd suggest we either validate everything or nothing at all. Performance may be affected, but first, I reckon, we have to decide whether we want this validation feature at all.

**Comment by DaQuirm** [comment]
After some consideration, I suggest removing all "on-send" validation: instead all services should have "on-receive/parse" validation and optionally respond with error messages. This way we handle messages from both "hostile" (users 😄 ) and "friendly" environment without any extra code.

**Comment by kirilknysh** [comment]
@DaQuirm , fair enough!

**Comment by DaQuirm** [comment]
@kirilknysh you mean the `checkin` message?

**Pull request merged**
